# Generated by Django 5.1.5 on 2025-03-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='dishesorder',
            options={'verbose_name_plural': 'Dishes Orders'},
        ),
    ]
