# Generated by Django 5.1.5 on 2025-03-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydishesorder',
            name='status',
            field=models.CharField(choices=[('not started', 'Not started'), ('ongoing', 'Ongoing'), ('cancelled', 'Cancelled'), ('done', 'Successfully finished'), ('stolen', 'Stolen')], max_length=50),
        ),
    ]
