# Generated by Django 5.1.5 on 2025-03-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_dish_options_alter_dishesorder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('provider', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.RemoveField(
            model_name='dishesorder',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'dishes'},
        ),
        migrations.AlterModelTable(
            name='dishorderitem',
            table=None,
        ),
    ]
